### ISSUE TITLE
Duplicating Slideshow

### ISSUE THREAD

**Issue by profWolfe** [themefisher/Small-Apps-Bootstrap-App-Landing-Template#1]
Hi Mehedi,

I'm using your website template and I want to customize it so that it shows two galleries. One after the other. However, when I cloned the HTML element for the gallery using clone() it doesn't repeat the CSS or JavaScript for the respected HTML.  How can I repeat the element and call the CSS and JavaScript so that I can repeat the slideshow?

Thanks,

James

**Comment by somratpro** [comment]
Hello @profWolfe 

We are sorry, we didn't notice your issue. hope you have solved your issue. I am closing it now. if you are stuck with other things, let me know. I am here to help you. thanks
